create schema nova_auction;
use nova_auction;

create table user_info(
id int PRIMARY key AUTO_INCREMENT,
first_name varchar(25),
last_name varchar(25),
email varchar(50),
pass varchar(50),
phonenumber varchar(20),
rule varchar(20) default 'User',
banned BOOLEAN NOT NULL DEFAULT false,
img_path Text default null --'/Nova-Auction/users_account_images/av.jpg'
);

create table cars(
id int PRIMARY key AUTO_INCREMENT,
makes_name varchar(50),
model_name varchar(50),
year_of_make int(4),
color varchar(40),
interiors text,
transmission varchar(40),
car_condition varchar(40),
fuel_type varchar(40)
);

create table items(
id int PRIMARY key AUTO_INCREMENT,
name varchar(1000),
des Text,
img_path Text ,
price int,
user_id int,
car_id int,
city_name varchar(20),
FOREIGN KEY (user_id) REFERENCES user_info(id),
FOREIGN KEY (car_id) REFERENCES cars(id)
);


create table city(
id int PRIMARY key AUTO_INCREMENT,
city_name varchar(20)
);

create table view_history(
id int PRIMARY key AUTO_INCREMENT,
user_id int,
car_id int,
price int,
foreign key (user_id) references user_info(id),
foreign key (car_id) references cars(id)
);

create table car_info(
id int PRIMARY key AUTO_INCREMENT,
makes_name varchar(50),
model_name varchar(50)
);

create table comment(
    id int PRIMARY key AUTO_INCREMENT,
    comment varchar(500),
    user_id int,
    item_id int,
    date_of_comment datetime,
FOREIGN KEY (user_id) REFERENCES user_info(id),
FOREIGN KEY (item_id) REFERENCES items(id)
);

create table notifications(
id int PRIMARY key AUTO_INCREMENT,
user_id int,
item_id int,    
type varchar(40),    
readed BOOLEAN NOT NULL DEFAULT false,
FOREIGN key (user_id) REFERENCES user_info(id),
FOREIGN key (item_id) REFERENCES items(id)
);

insert into car_info values
    (default,'Mercedes-Benz','A-Class'),
    (default,'Audi','A3'),
    (default,'Audi','A4'),
    (default,'Audi','A4 allroad'),
    (default,'Audi','A5'),
    (default,'Audi','A6'),
    (default,'Audi','A6 allroad'),
    (default,'Audi','A7'),
    (default,'Audi','A8'),
    (default,'GMC','Acadia'),
    (default,'Hyundai','Accent'),
    (default,'Honda','Accord'),
    (default,'Honda','Accord Hybrid'),
    (default,'Lucid','Air'),
    (default,'Nissan','Altima'),
    (default,'Nissan','Ariya'),
    (default,'Nissan','Armada'),
    (default,'Volkswagen','Arteon'),
    (default,'Subaru','Ascent'),
    (default,'Volkswagen','Atlas'),
    (default,'Volkswagen','Atlas Cross Sport'),
    (default,'Toyota','Avalon'),
    (default,'Toyota','Avalon Hybrid'),
    (default,'Lamborghini','Aventador'),
    (default,'Lincoln','Aviator'),
    (default,'Bentley','Bentayga'),
    (default,'Chevrolet','Blazer'),
    (default,'Chevrolet','Blazer EV'),
    (default,'Chevrolet','Bolt EUV'),
    (default,'Chevrolet','Bolt EV'),
    (default,'Ford','Bronco'),
    (default,'Ford','Bronco Sport'),
    (default,'Subaru','BRZ'),
    (default,'Toyota','bZ4X'),
    (default,'Mercedes-Benz','C-Class'),
    (default,'Toyota','C-HR'),
    (default,'Volvo','C40 Recharge'),
    (default,'Chevrolet','Camaro'),
    (default,'Toyota','Camry'),
    (default,'Toyota','Camry Hybrid'),
    (default,'GMC','Canyon Crew Cab'),
    (default,'GMC','Canyon Extended Cab'),
    (default,'Kia','Carnival'),
    (default,'Porsche','Cayenne'),
    (default,'Porsche','Cayenne Coupe'),
    (default,'Cadillac','Celestiq'),
    (default,'Dodge','Challenger'),
    (default,'Dodge','Charger'),
    (default,'Jeep','Cherokee'),
    (default,'Honda','Civic'),
    (default,'Honda','Civic Type R'),
    (default,'Mercedes-Benz','CLA'),
    (default,'Honda','Clarity Fuel Cell'),
    (default,'Honda','Clarity Plug-in Hybrid'),
    (default,'Mercedes-Benz','CLS'),
    (default,'MINI','Clubman'),
    (default,'Chevrolet','Colorado Crew Cab'),
    (default,'Chevrolet','Colorado Extended Cab'),
    (default,'Jeep','Compass'),
    (default,'Bentley','Continental GT'),
    (default,'MINI','Convertible'),
    (default,'Toyota','Corolla'),
    (default,'Toyota','Corolla Cross'),
    (default,'Toyota','Corolla Cross Hybrid'),
    (default,'Toyota','Corolla Hatchback'),
    (default,'Toyota','Corolla Hybrid'),
    (default,'Lincoln','Corsair'),
    (default,'Chevrolet','Corvette'),
    (default,'MINI','Countryman'),
    (default,'Honda','CR-V'),
    (default,'Honda','CR-V Hybrid'),
    (default,'Subaru','Crosstrek'),
    (default,'Toyota','Crown'),
    (default,'Cadillac','CT4'),
    (default,'Cadillac','CT5'),
    (default,'Rolls-Royce','Cullinan'),
    (default,'MAZDA','CX-3'),
    (default,'MAZDA','CX-30'),
    (default,'MAZDA','CX-5'),
    (default,'MAZDA','CX-50'),
    (default,'MAZDA','CX-70'),
    (default,'MAZDA','CX-9'),
    (default,'MAZDA','CX-90'),
    (default,'Tesla','Cybertruck'),
    (default,'Rolls-Royce','Dawn'),
    (default,'Aston Martin','DB11'),
    (default,'Aston Martin','DBS'),
    (default,'Aston Martin','DBX'),
    (default,'Land Rover','Defender 110'),
    (default,'Land Rover','Defender 130'),
    (default,'Land Rover','Defender 90'),
    (default,'Land Rover','Discovery'),
    (default,'Land Rover','Discovery Sport'),
    (default,'Dodge','Durango'),
    (default,'Mercedes-Benz','E-Class'),
    (default,'Jaguar','E-PACE'),
    (default,'Ford','E-Transit 350 Cargo Van'),
    (default,'Audi','e-tron'),
    (default,'Audi','e-tron GT'),
    (default,'Audi','e-tron S'),
    (default,'Audi','e-tron S Sportback'),
    (default,'Audi','e-tron Sportback'),
    (default,'Mitsubishi','Eclipse Cross'),
    (default,'Ford','EcoSport'),
    (default,'Ford','Edge'),
    (default,'Hyundai','Elantra'),
    (default,'Hyundai','Elantra Hybrid'),
    (default,'Hyundai','Elantra N'),
    (default,'Genesis','Electrified G80'),
    (default,'Genesis','Electrified GV70'),
    (default,'Buick','Enclave'),
    (default,'Buick','Encore'),
    (default,'Buick','Encore GX'),
    (default,'Buick','Envision'),
    (default,'Chevrolet','Equinox'),
    (default,'Chevrolet','Equinox EV'),
    (default,'Lexus','ES'),
    (default,'Cadillac','Escalade'),
    (default,'Cadillac','Escalade ESV'),
    (default,'Ford','Escape'),
    (default,'Ford','Escape Plug-in Hybrid'),
    (default,'Kia','EV6'),
    (default,'Kia','EV9'),
    (default,'Lotus','Evora GT'),
    (default,'Volvo','EX90'),
    (default,'Ford','Expedition'),
    (default,'Ford','Expedition MAX'),
    (default,'Ford','Explorer'),
    (default,'Chevrolet','Express 2500 Cargo'),
    (default,'Chevrolet','Express 2500 Passenger'),
    (default,'Chevrolet','Express 3500 Cargo'),
    (default,'Chevrolet','Express 3500 Passenger'),
    (default,'Jaguar','F-PACE'),
    (default,'Jaguar','F-TYPE'),
    (default,'Ford','F150 Lightning'),
    (default,'Ford','F150 Regular Cab'),
    (default,'Ford','F150 Super Cab'),
    (default,'Ford','F150 SuperCrew Cab'),
    (default,'Ford','F250 Super Duty Crew Cab'),
    (default,'Ford','F250 Super Duty Regular Cab'),
    (default,'Ford','F250 Super Duty Super Cab'),
    (default,'Ford','F350 Super Duty Crew Cab'),
    (default,'Ford','F350 Super Duty Regular Cab'),
    (default,'Ford','F350 Super Duty Super Cab'),
    (default,'Ford','F450 Super Duty Crew Cab'),
    (default,'Ford','F450 Super Duty Regular Cab'),
    (default,'Ferrari','F8'),
    (default,'Bentley','Flying Spur'),
    (default,'Subaru','Forester'),
    (default,'Kia','Forte'),
    (default,'Nissan','Frontier Crew Cab'),
    (default,'Nissan','Frontier King Cab'),
    (default,'Mercedes-Benz','G-Class'),
    (default,'Genesis','G70'),
    (default,'Genesis','G80'),
    (default,'Genesis','G90'),
    (default,'Maserati','Ghibli'),
    (default,'Rolls-Royce','Ghost'),
    (default,'Alfa Romeo','Giulia'),
    (default,'Mercedes-Benz','GLA'),
    (default,'Jeep','Gladiator'),
    (default,'Mercedes-Benz','GLB'),
    (default,'Mercedes-Benz','GLC'),
    (default,'Mercedes-Benz','GLC Coupe'),
    (default,'Mercedes-Benz','GLE'),
    (default,'Mercedes-Benz','GLS'),
    (default,'Volkswagen','Golf GTI'),
    (default,'Volkswagen','Golf R'),
    (default,'Toyota','GR Corolla'),
    (default,'Toyota','GR Supra'),
    (default,'Toyota','GR86'),
    (default,'Jeep','Grand Cherokee'),
    (default,'Jeep','Grand Cherokee 4xe'),
    (default,'Jeep','Grand Cherokee L'),
    (default,'Toyota','Grand Highlander'),
    (default,'Jeep','Grand Wagoneer'),
    (default,'Jeep','Grand Wagoneer L'),
    (default,'Maserati','Grecale'),
    (default,'Nissan','GT-R'),
    (default,'Genesis','GV60'),
    (default,'Genesis','GV70'),
    (default,'Genesis','GV80'),
    (default,'Lexus','GX'),
    (default,'MINI','Hardtop 2 Door'),
    (default,'MINI','Hardtop 4 Door'),
    (default,'Toyota','Highlander'),
    (default,'Toyota','Highlander Hybrid'),
    (default,'Dodge','Hornet'),
    (default,'Honda','HR-V'),
    (default,'GMC','Hummer EV Pickup'),
    (default,'GMC','Hummer EV SUV'),
    (default,'Lamborghini','Huracan'),
    (default,'Jaguar','I-PACE'),
    (default,'BMW','i3'),
    (default,'BMW','i4'),
    (default,'BMW','i7'),
    (default,'Volkswagen','ID.4'),
    (default,'Volkswagen','ID.Buzz'),
    (default,'Acura','ILX'),
    (default,'Subaru','Impreza'),
    (default,'Honda','Insight'),
    (default,'Acura','Integra'),
    (default,'Hyundai','IONIQ 5'),
    (default,'Hyundai','IONIQ 6'),
    (default,'Hyundai','IONIQ 7'),
    (default,'Hyundai','Ioniq Electric'),
    (default,'Hyundai','Ioniq Hybrid'),
    (default,'Hyundai','Ioniq Plug-in Hybrid'),
    (default,'Lexus','IS'),
    (default,'BMW','iX'),
    (default,'Volkswagen','Jetta'),
    (default,'Volkswagen','Jetta GLI'),
    (default,'Kia','K5'),
    (default,'Nissan','Kicks'),
    (default,'Hyundai','Kona'),
    (default,'Hyundai','Kona Electric'),
    (default,'Hyundai','Kona N'),
    (default,'Toyota','Land Cruiser'),
    (default,'Lexus','LC'),
    (default,'Nissan','LEAF'),
    (default,'Subaru','Legacy'),
    (default,'Maserati','Levante'),
    (default,'Lexus','LS'),
    (default,'Lexus','LX'),
    (default,'Cadillac','LYRIQ'),
    (default,'BMW','M2'),
    (default,'BMW','M3'),
    (default,'BMW','M4'),
    (default,'BMW','M5'),
    (default,'BMW','M8'),
    (default,'Porsche','Macan'),
    (default,'Chevrolet','Malibu'),
    (default,'Ford','Maverick'),
    (default,'Nissan','Maxima'),
    (default,'MAZDA','MAZDA3'),
    (default,'MAZDA','MAZDA6'),
    (default,'Maserati','MC20'),
    (default,'Acura','MDX'),
    (default,'Mercedes-Benz','Mercedes-AMG A-Class'),
    (default,'Mercedes-Benz','Mercedes-AMG C-Class'),
    (default,'Mercedes-Benz','Mercedes-AMG CLA'),
    (default,'Mercedes-Benz','Mercedes-AMG CLS'),
    (default,'Mercedes-Benz','Mercedes-AMG E-Class'),
    (default,'Mercedes-Benz','Mercedes-AMG EQS'),
    (default,'Mercedes-Benz','Mercedes-AMG G-Class'),
    (default,'Mercedes-Benz','Mercedes-AMG GLA'),
    (default,'Mercedes-Benz','Mercedes-AMG GLB'),
    (default,'Mercedes-Benz','Mercedes-AMG GLC'),
    (default,'Mercedes-Benz','Mercedes-AMG GLC Coupe'),
    (default,'Mercedes-Benz','Mercedes-AMG GLE'),
    (default,'Mercedes-Benz','Mercedes-AMG GLE Coupe'),
    (default,'Mercedes-Benz','Mercedes-AMG GLS'),
    (default,'Mercedes-Benz','Mercedes-AMG GT'),
    (default,'Mercedes-Benz','Mercedes-AMG S-Class'),
    (default,'Mercedes-Benz','Mercedes-AMG SL'),
    (default,'Mercedes-Benz','Mercedes-EQ EQB'),
    (default,'Mercedes-Benz','Mercedes-EQ EQE'),
    (default,'Mercedes-Benz','Mercedes-EQ EQE SUV'),
    (default,'Mercedes-Benz','Mercedes-EQ EQS'),
    (default,'Mercedes-Benz','Mercedes-EQ EQS SUV'),
    (default,'Mercedes-Benz','Mercedes-Maybach GLS'),
    (default,'Mercedes-Benz','Mercedes-Maybach S-Class'),
    (default,'Mercedes-Benz','Metris Cargo'),
    (default,'Mercedes-Benz','Metris Passenger'),
    (default,'Mitsubishi','Mirage'),
    (default,'Mitsubishi','Mirage G4'),
    (default,'Toyota','Mirai'),
    (default,'Tesla','Model 3'),
    (default,'Tesla','Model S'),
    (default,'Tesla','Model X'),
    (default,'Tesla','Model Y'),
    (default,'Nissan','Murano'),
    (default,'Ford','Mustang'),
    (default,'Ford','Mustang MACH-E'),
    (default,'MAZDA','MX-30'),
    (default,'MAZDA','MX-5 Miata'),
    (default,'MAZDA','MX-5 Miata RF'),
    (default,'Lincoln','Nautilus'),
    (default,'Lincoln','Navigator'),
    (default,'Lincoln','Navigator L'),
    (default,'Hyundai','NEXO'),
    (default,'Kia','Niro'),
    (default,'Kia','Niro EV'),
    (default,'Kia','Niro Plug-in Hybrid'),
    (default,'Acura','NSX'),
    (default,'Nissan','NV1500 Cargo'),
    (default,'Nissan','NV200'),
    (default,'Nissan','NV2500 HD Cargo'),
    (default,'Nissan','NV3500 HD Cargo'),
    (default,'Nissan','NV3500 HD Passenger'),
    (default,'Lexus','NX'),
    (default,'Fisker','Ocean'),
    (default,'Honda','Odyssey'),
    (default,'Subaru','Outback'),
    (default,'Mitsubishi','Outlander'),
    (default,'Mitsubishi','Outlander PHEV'),
    (default,'Mitsubishi','Outlander Sport'),
    (default,'Chrysler','Pacifica'),
    (default,'Chrysler','Pacifica Hybrid'),
    (default,'Hyundai','Palisade'),
    (default,'Porsche','Panamera'),
    (default,'Volkswagen','Passat'),
    (default,'Honda','Passport'),
    (default,'Nissan','Pathfinder'),
    (default,'Rolls-Royce','Phantom'),
    (default,'Honda','Pilot'),
    (default,'Ferrari','Portofino'),
    (default,'Toyota','Prius'),
    (default,'Toyota','Prius Prime'),
    (default,'Honda','Prologue'),
    (default,'Ram','ProMaster Cargo Van'),
    (default,'Ram','ProMaster City'),
    (default,'Ram','ProMaster Window Van'),
    (default,'Audi','Q3'),
    (default,'Audi','Q4 e-tron'),
    (default,'Audi','Q4 Sportback e-tron'),
    (default,'Audi','Q5'),
    (default,'Audi','Q5 Sportback'),
    (default,'INFINITI','Q50'),
    (default,'INFINITI','Q60'),
    (default,'Audi','Q7'),
    (default,'Audi','Q8'),
    (default,'Audi','Q8 e-tron'),
    (default,'Maserati','Quattroporte'),
    (default,'INFINITI','QX50'),
    (default,'INFINITI','QX55'),
    (default,'INFINITI','QX60'),
    (default,'INFINITI','QX80'),
    (default,'Rivian','R1S'),
    (default,'Rivian','R1T'),
    (default,'Audi','R8'),
    (default,'Land Rover','Range Rover'),
    (default,'Land Rover','Range Rover Evoque'),
    (default,'Land Rover','Range Rover Sport'),
    (default,'Land Rover','Range Rover Velar'),
    (default,'Ford','Ranger SuperCab'),
    (default,'Ford','Ranger SuperCrew'),
    (default,'Toyota','RAV4'),
    (default,'Toyota','RAV4 Hybrid'),
    (default,'Toyota','RAV4 Prime'),
    (default,'Lexus','RC'),
    (default,'Acura','RDX'),
    (default,'Jeep','Recon'),
    (default,'Jeep','Renegade'),
    (default,'Honda','Ridgeline'),
    (default,'Kia','Rio'),
    (default,'Nissan','Rogue'),
    (default,'Nissan','Rogue Sport'),
    (default,'Ferrari','Roma'),
    (default,'Audi','RS 3'),
    (default,'Audi','RS 5'),
    (default,'Audi','RS 6'),
    (default,'Audi','RS 7'),
    (default,'Audi','RS e-tron GT'),
    (default,'Audi','RS Q8'),
    (default,'Lexus','RX'),
    (default,'Lexus','RZ'),
    (default,'Mercedes-Benz','S-Class'),
    (default,'Audi','S3'),
    (default,'Audi','S4'),
    (default,'Audi','S5'),
    (default,'Audi','S6'),
    (default,'Volvo','S60'),
    (default,'Audi','S7'),
    (default,'Audi','S8'),
    (default,'Volvo','S90'),
    (default,'Hyundai','Santa Cruz'),
    (default,'Hyundai','Santa Fe'),
    (default,'Hyundai','Santa Fe Hybrid'),
    (default,'Hyundai','Santa Fe Plug-in Hybrid'),
    (default,'GMC','Savana 2500 Cargo'),
    (default,'GMC','Savana 2500 Passenger'),
    (default,'GMC','Savana 3500 Cargo'),
    (default,'GMC','Savana 3500 Passenger'),
    (default,'Kia','Sedona'),
    (default,'Kia','Seltos'),
    (default,'Nissan','Sentra'),
    (default,'Toyota','Sequoia'),
    (default,'Ferrari','SF90'),
    (default,'Toyota','Sienna'),
    (default,'GMC','Sierra 1500 Crew Cab'),
    (default,'GMC','Sierra 1500 Double Cab'),
    (default,'GMC','Sierra 1500 Limited Crew Cab'),
    (default,'GMC','Sierra 1500 Limited Double Cab'),
    (default,'GMC','Sierra 1500 Limited Regular Cab'),
    (default,'GMC','Sierra 1500 Regular Cab'),
    (default,'GMC','Sierra 2500 HD Crew Cab'),
    (default,'GMC','Sierra 2500 HD Double Cab'),
    (default,'GMC','Sierra 2500 HD Regular Cab'),
    (default,'GMC','Sierra 3500 HD Crew Cab'),
    (default,'GMC','Sierra 3500 HD Double Cab'),
    (default,'GMC','Sierra 3500 HD Regular Cab'),
    (default,'GMC','Sierra EV'),
    (default,'Chevrolet','Silverado 1500 Crew Cab'),
    (default,'Chevrolet','Silverado 1500 Double Cab'),
    (default,'Chevrolet','Silverado 1500 Limited Crew Cab'),
    (default,'Chevrolet','Silverado 1500 Limited Double Cab'),
    (default,'Chevrolet','Silverado 1500 Limited Regular Cab'),
    (default,'Chevrolet','Silverado 1500 Regular Cab'),
    (default,'Chevrolet','Silverado 2500 HD Crew Cab'),
    (default,'Chevrolet','Silverado 2500 HD Double Cab'),
    (default,'Chevrolet','Silverado 2500 HD Regular Cab'),
    (default,'Chevrolet','Silverado 3500 HD Crew Cab'),
    (default,'Chevrolet','Silverado 3500 HD Double Cab'),
    (default,'Chevrolet','Silverado 3500 HD Regular Cab'),
    (default,'Chevrolet','Silverado EV'),
    (default,'Subaru','Solterra'),
    (default,'Hyundai','Sonata'),
    (default,'Hyundai','Sonata Hybrid'),
    (default,'Kia','Sorento'),
    (default,'Kia','Sorento Hybrid'),
    (default,'Kia','Sorento Plug-in Hybrid'),
    (default,'Kia','Soul'),
    (default,'Chevrolet','Spark'),
    (default,'Kia','Sportage'),
    (default,'Kia','Sportage Hybrid'),
    (default,'Kia','Sportage Plug-in Hybrid'),
    (default,'Freightliner','Sprinter 1500 Cargo'),
    (default,'Mercedes-Benz','Sprinter 1500 Cargo'),
    (default,'Freightliner','Sprinter 1500 Passenger'),
    (default,'Mercedes-Benz','Sprinter 1500 Passenger'),
    (default,'Freightliner','Sprinter 2500 Cargo'),
    (default,'Mercedes-Benz','Sprinter 2500 Cargo'),
    (default,'Freightliner','Sprinter 2500 Crew'),
    (default,'Mercedes-Benz','Sprinter 2500 Crew'),
    (default,'Freightliner','Sprinter 2500 Passenger'),
    (default,'Mercedes-Benz','Sprinter 2500 Passenger'),
    (default,'Freightliner','Sprinter 3500 Cargo'),
    (default,'Mercedes-Benz','Sprinter 3500 Cargo'),
    (default,'Freightliner','Sprinter 3500 Crew'),
    (default,'Mercedes-Benz','Sprinter 3500 Crew'),
    (default,'Mercedes-Benz','Sprinter 3500 XD Cargo'),
    (default,'Freightliner','Sprinter 3500 XD Crew'),
    (default,'Mercedes-Benz','Sprinter 3500 XD Crew'),
    (default,'Freightliner','Sprinter 3500XD Cargo'),
    (default,'Freightliner','Sprinter 4500 Cargo'),
    (default,'Mercedes-Benz','Sprinter 4500 Cargo'),
    (default,'Freightliner','Sprinter 4500 Crew'),
    (default,'Mercedes-Benz','Sprinter 4500 Crew'),
    (default,'Audi','SQ5'),
    (default,'Audi','SQ5 Sportback'),
    (default,'Audi','SQ7'),
    (default,'Audi','SQ8'),
    (default,'Alfa Romeo','Stelvio'),
    (default,'Kia','Stinger'),
    (default,'Chevrolet','Suburban'),
    (default,'Toyota','Tacoma Access Cab'),
    (default,'Toyota','Tacoma Double Cab'),
    (default,'Chevrolet','Tahoe'),
    (default,'Volkswagen','Taos'),
    (default,'Porsche','Taycan'),
    (default,'Porsche','Taycan Cross Turismo'),
    (default,'Kia','Telluride'),
    (default,'GMC','Terrain'),
    (default,'Volkswagen','Tiguan'),
    (default,'Nissan','Titan Crew Cab'),
    (default,'Nissan','Titan King Cab'),
    (default,'Nissan','TITAN XD Crew Cab'),
    (default,'Acura','TLX'),
    (default,'Alfa Romeo','Tonale'),
    (default,'Chevrolet','Trailblazer'),
    (default,'Ford','Transit 150 Cargo Van'),
    (default,'Ford','Transit 150 Crew Van'),
    (default,'Ford','Transit 150 Passenger Van'),
    (default,'Ford','Transit 250 Cargo Van'),
    (default,'Ford','Transit 250 Crew Van'),
    (default,'Ford','Transit 350 Cargo Van'),
    (default,'Ford','Transit 350 Crew Van'),
    (default,'Ford','Transit 350 HD Cargo Van'),
    (default,'Ford','Transit 350 HD Crew Van'),
    (default,'Ford','Transit 350 Passenger Van'),
    (default,'Ford','Transit Connect Cargo Van'),
    (default,'Ford','Transit Connect Passenger Wagon'),
    (default,'Chevrolet','Traverse'),
    (default,'Chevrolet','Trax'),
    (default,'Audi','TT'),
    (default,'Hyundai','Tucson'),
    (default,'Hyundai','Tucson Hybrid'),
    (default,'Hyundai','Tucson Plug-in Hybrid'),
    (default,'Toyota','Tundra CrewMax'),
    (default,'Toyota','Tundra Double Cab'),
    (default,'Toyota','Tundra Hybrid CrewMax'),
    (default,'Lexus','TX'),
    (default,'Lamborghini','Urus'),
    (default,'Lexus','UX'),
    (default,'Volvo','V60'),
    (default,'Volvo','V90'),
    (default,'Aston Martin','Vantage'),
    (default,'Hyundai','Veloster'),
    (default,'Hyundai','Venue'),
    (default,'Toyota','Venza'),
    (default,'Nissan','Versa'),
    (default,'VinFast','VF 6'),
    (default,'VinFast','VF 7'),
    (default,'VinFast','VF 8'),
    (default,'VinFast','VF 9'),
    (default,'Jeep','Wagoneer'),
    (default,'Jeep','Wagoneer L'),
    (default,'Rolls-Royce','Wraith'),
    (default,'Jeep','Wrangler'),
    (default,'Jeep','Wrangler 4xe'),
    (default,'Jeep','Wrangler Unlimited'),
    (default,'Jeep','Wrangler Unlimited 4xe'),
    (default,'Subaru','WRX'),
    (default,'BMW','X1'),
    (default,'BMW','X2'),
    (default,'BMW','X3'),
    (default,'BMW','X3 M'),
    (default,'BMW','X4'),
    (default,'BMW','X4 M'),
    (default,'BMW','X5'),
    (default,'BMW','X5 M'),
    (default,'BMW','X6'),
    (default,'BMW','X6 M'),
    (default,'BMW','X7'),
    (default,'Volvo','XC40'),
    (default,'Volvo','XC40 Recharge'),
    (default,'Volvo','XC60'),
    (default,'Volvo','XC90'),
    (default,'Jaguar','XF'),
    (default,'BMW','XM'),
    (default,'Cadillac','XT4'),
    (default,'Cadillac','XT5'),
    (default,'Cadillac','XT6'),
    (default,'GMC','Yukon'),
    (default,'GMC','Yukon XL'),
    (default,'Nissan','Z'),
    (default,'BMW','Z4'),
    (default,'Polestar','1'),
    (default,'Ram','1500 Classic Crew Cab'),
    (default,'Ram','1500 Classic Quad Cab'),
    (default,'Ram','1500 Classic Regular Cab'),
    (default,'Ram','1500 Crew Cab'),
    (default,'Ram','1500 Quad Cab'),
    (default,'Polestar','2'),
    (default,'BMW','2 Series'),
    (default,'Ram','2500 Crew Cab'),
    (default,'Ram','2500 Mega Cab'),
    (default,'Ram','2500 Regular Cab'),
    (default,'Ferrari','296 GTB'),
    (default,'Polestar','3'),
    (default,'BMW','3 Series'),
    (default,'Chrysler','300'),
    (default,'Ram','3500 Crew Cab'),
    (default,'Ram','3500 Mega Cab'),
    (default,'Ram','3500 Regular Cab'),
    (default,'BMW','4 Series'),
    (default,'Ferrari','488 Pista'),
    (default,'Toyota','4Runner'),
    (default,'Polestar','5'),
    (default,'BMW','5 Series'),
    (default,'FIAT','500X'),
    (default,'BMW','7 Series'),
    (default,'Porsche','718 Boxster'),
    (default,'Porsche','718 Cayman'),
    (default,'Porsche','718 Spyder'),
    (default,'BMW','8 Series'),
    (default,'Ferrari','812 Competizione'),
    (default,'Ferrari','812 Competizione A'),
    (default,'Ferrari','812 GTS'),
    (default,'Ferrari','812 Superfast'),
    (default,'Toyota','86'),
    (default,'Porsche','911');

insert into city values
    (default,'ajloun'),
    (default,'amman'),
    (default,'aqaba'),
    (default,'balqa'),
    (default,'irbid'),
    (default,'jerash'),
    (default,'karak'),
    (default,'maan'),
    (default,'madaba'),
    (default,'mafraq'),
    (default,'tafilah'),
    (default,'zarqa');
